version: '3'
services:
  em-caja-digital-backend:
    container_name: em-caja-digital-backend
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    ports:
      - 3000:3000
    command: npm run start:prod