version: '3'

services:
  em-caja-digital-backend:
    image: em-caja-digital-backend:dev
    env_file:
      - .env
    build:
      dockerfile: ./Dockerfile.back.dev
      context: ./
    container_name: em-caja-digital-backend
    volumes:
      - ./:/app/
      - emcajadigitalback:/app/node_modules
    command: "npm run start:debug"
    networks:
      - work
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - pgsql-example
  
  pgsql-example:
    image: postgres:14.0-alpine
    container_name: pgsql-example
    networks:
      - work
    ports:
      - 5433:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "cash_admin"
      POSTGRES_PASSWORD: "4639802"
      POSTGRES_DB: "caja2"

networks:
  work:

volumes:
  data:
  emcajadigitalback: